### ISSUE TITLE
Add config file to NOAA NOS fetch step

### ISSUE THREAD

**Issue by amsnyder** [USGS-R/drb-estuary-salinity-ml#21]
pull variables that might change from NOAA NOS fetch step into a config file

**Comment by amsnyder** [comment]
@ted80 - we will need to make a decision about how many config files to have before we do this

**Comment by ted80810** [comment]
I think one config file per step (fetch, munge etc) would work if you think it won't be confusing to users. My real concern is that usgs stations and noaa stations are different, so a user might accidently call site_ids in the fetch_noaa_nos function if both are in the same config file. At the same time, we call site_ids for usgs and station_ids for noaa, so that might be the only step necessary to avoid mistakes. What are your thoughts? @amsnyder

**Comment by amsnyder** [comment]
One file per step makes sense to me! Then within the file, we can have one section per script, so you only read in the variables relevant to that script. I will make an update, and add a comment in this thread once I do.

**Comment by amsnyder** [comment]
@ted80810 - I updated the config file. You will see a spot in each for you to add your NOAA NOS variables, but let me know if you have any questions about what I did!
